service: kpi-udm
frameworkVersion: "3"

package:

  include:
    - es_controller.py
    - lambda_function.py
provider:
  name: aws
  runtime: python3.8
  region: ap-south-1
  stage: prod



functions:
  encounter-superset:
    handler: handler.encounter-superset
    events:
      - http:
          path: /EncounterSearch
          method: post

